name: flutter_app2
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  device_preview:
  sizer:

  shared_preferences: ^2.0.5
  animated_splash_screen:
  smooth_page_indicator:
  flutter_svg:
  bloc:
  flutter_bloc: ^8.0.1
  connectivity:
  one_context:
  cloud_firestore: ^3.1.9
  dio:
  fluttertoast:
  firebase_core:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
